name: Deploy Apache to DEV

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy-dev:
    # 「develop に向けた PR が merge された時のみ」
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DEV EC2 (Apache)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/apache-proxy
            git pull origin develop
            sudo cp proxy.conf /etc/httpd/conf.d/proxy.conf
            sudo apachectl -t
            sudo systemctl restart httpd